### ISSUE TITLE
For some reason my events get 20 minutes added to them?

### ISSUE THREAD

**Issue by dubcanada** [Appgutta/AGCalendar#11]
Hello,

I have an application that creates a start date object for say "2012-08-21 17:59:44 +0000"

And when I go and look in the calendar my events are "2012-08-21 18:19:44 +0000"

So somewhere 20 minutes is being added in the module or my iPhone (4 with 5.1.1 btw)

Any idea? I haven't tested it in another phone yet, I'll do that tomorrow and post the results.

**Comment by ChrisRM** [comment]
Please post an update after you've tested it with another device. This sounds pretty wierd

**Comment by dubcanada** [comment]
I tested it with 3 other phones.

Anything going into Ag.Calendar module by javascript is correct, anything coming out has 20 minutes added onto it. (I tested a variety of dates and times).

**Comment by dubcanada** [comment]
If I subtract 20 minutes from the javascript time before I send it over, it works perfectly fine.

:)

**Comment by rossmd** [comment]
I'm having the exact same issue.  Tested on iPhone 4 and 4S.  Sending a javascript date of '2012-09-10 23:00:00 +0000' and the event is starting at 2012-09-10 18:20:00 (CST).

I should note im using Ti 2.1.2.GA SDK and 2.1.2 Studio

**Comment by rossmd** [comment]
Any update on this?

**Comment by ChrisRM** [comment]
Oh, totally forgot about this issue. I located the problem now, so I just have to make some minor changes before I upload the new build.
