### ISSUE TITLE
Slim version?

### ISSUE THREAD

**Issue by dubcanada** [Appgutta/AGCalendar#12]
Hello,

I am wondering if it is possible to just have the eventkit part? I just want to be able to add events to the native iOS calendar. I don't need any of the other fancy stuff.

Is that possible?

**Comment by ChrisRM** [comment]
You dont need to use the calendar view. Just set eventkit as your datasource and start adding events to the calendar. The main thing missing is the option to retrieve events as lists(array/objects). I'll see if I can add that functionality. Pretty busy atm, but I'll try to make room for it.

**Comment by ChrisRM** [comment]
Fixed in https://github.com/Appgutta/AGCalendar/commit/4b3d1edda7e7a0dca591e8c0aacde6a7d378cb82
