### ISSUE TITLE
Error building in Ti Studio

### ISSUE THREAD

**Issue by rossmd** [Appgutta/AGCalendar#13]
I just downloaded the latest build (with fixes for my other issue #11) and build the module locally.  I'm using SDK 2.1.3.v20120915120319.  The build works (no errors) and I add the module's zip file to Titanium.

But when I try to run my code using the simulator or build for Distribution, I get the following error:

[INFO] Minimum iOS version: 4.0
[INFO] Performing clean build
[ERROR] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] 
[ERROR] Error: Traceback (most recent call last):
  File "/Users/rossmd/Library/Application Support/Titanium/mobilesdk/osx/2.1.3.v20120915120319/iphone/builder.py", line 1466, in main
    execute_xcode("iphoneos%s" % iphone_version,args,False)
  File "/Users/rossmd/Library/Application Support/Titanium/mobilesdk/osx/2.1.3.v20120915120319/iphone/builder.py", line 1221, in execute_xcode
    output = run.run(args,False,False,o)
  File "/Users/rossmd/Library/Application Support/Titanium/mobilesdk/osx/2.1.3.v20120915120319/iphone/run.py", line 41, in run
    sys.exit(rc)
SystemExit: 65

**Comment by ChrisRM** [comment]
I'll have a look later tonight. UTC/GMT +1

**Comment by exojason** [comment]
I'm getting the same error.

**Comment by rossmd** [comment]
I re-compiled the module using Titanium 2.1.3.GA (just released) and the module compiled without issue and I'm able to run my program.  However, when I try to save an event to my phone's calendar from my app, nothing happens.  And I assume this is because iOS 6 requires permission to access Calendar:

https://developer.apple.com/library/ios/#documentation/DataManagement/Conceptual/EventKitProgGuide/ReadingAndWritingEvents.html#//apple_ref/doc/uid/TP40004775-SW1

**Comment by ChrisRM** [comment]
Try the newest build

**Comment by rossmd** [comment]
Yes its working now.  Thanks a lot of updating this!!
