### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by mikehobson** [Appgutta/AGCalendar#14]
Hi Chris
Is it possible to be able to select the calendar the event is added to ?

Also is there a way to output an error messages, on all other modules Ive tried I get an error "No Calendar has been set" when I use the modules on my device, it looks like it could be the same on your module but I can't see a way to output an error

Thanks

Mike

**Comment by ChrisRM** [comment]
Fixed in version 2.0 which will be available in the Marketplace soon.
