### ISSUE TITLE
iOS6: Can't add new event

### ISSUE THREAD

**Issue by terenzeyuen** [Appgutta/AGCalendar#15]
Hi guys,

I keep getting this message when I try to add an event in iOS6, it was working fine in iOS5.

defaultCalendarForNewEvents failed: Error Domain=EKCADErrorDomain Code=1013 "The operation couldn’t be completed. (EKCADErrorDomain error 1013.)"

Googled this:
http://stackoverflow.com/questions/12454324/defaultcalendarfornewevents-failed

I've tried using the latest zip file from installation but it seems to be dated 2 months old? However I do see some files were updated recently...can you please update the zip file too as I use it for per project module method?

Thanks!
T

**Comment by ChrisRM** [comment]
Download the newest build. Should work.
