### ISSUE TITLE
Couldn't find module: ag.calendar

### ISSUE THREAD

**Issue by rhayun** [Appgutta/AGCalendar#16]
no matter where i put the module.. if its on the : ~/Library/Application Support/Titanium/modules/iphone or in /Library/Application Support/Titanium/modules/iphone
also when i put it on the project root 

the module is exist but i still get the "[ERROR] Script Error = Couldn't find module: ag.calendar." when i run it o the simulator

i use it on iOS6 SDK and xCode 4.5.1 with the latest Titanium SDK 2.1.3.GA

**Comment by rhayun** [comment]
ok sorry my bad.. i have to clean and rebuild again.. problem solved!

**Comment by ChrisRM** [comment]
Great! :+1:
