### ISSUE TITLE
Device app crashing due to /usr/lib/libobjc.A.dylib

### ISSUE THREAD

**Issue by schmoove** [Appgutta/AGCalendar#19]
Just re-checked this bug on today's latest build in case it was fixed by the latest commit, but still happening. If I include and init the calendar in my app I get the following output from Xcode when the app crashes while running on device:

[DEBUG] Loading: /var/mobile/Applications/ABC7F2D9-5E20-4CEC-B6A4-0CE8D279AC74/Syngency.app/ag.calendar.js, Resource: ag_calendar_js
dyld: lazy symbol binding failed: Symbol not found: _objc_setProperty_nonatomic
  Referenced from: /var/mobile/Applications/ABC7F2D9-5E20-4CEC-B6A4-0CE8D279AC74/Syngency.app/Syngency
  Expected in: /usr/lib/libobjc.A.dylib

dyld: Symbol not found: _objc_setProperty_nonatomic
  Referenced from: /var/mobile/Applications/ABC7F2D9-5E20-4CEC-B6A4-0CE8D279AC74/Syngency.app/Syngency
  Expected in: /usr/lib/libobjc.A.dylib

(tested with Ti SDK 2.1.1.GA and 2.1.3.GA)

If I comment out the calendar and re-build app runs normally. Could I be doing something wrong?
Thanks

**Comment by schmoove** [comment]
Researching this further, could this be an issue?

http://stackoverflow.com/questions/12573685/runtime-exception-after-upgrade-to-xcode4-5-ios6-base-sdk

Have attempted to change the deployment target version in my Xcode project but with same result.

**Comment by ChrisRM** [comment]
Great find, I'll see what I can do.

**Comment by annakozy2011** [comment]
I am also having this problem. I am not sure, if it's only ios-5 related or also happens on ios-6

**Comment by annakozy2011** [comment]
I think I worked it out. It's indeed the problem of target version, I set it to 5.0 and then it worked (namely, it was set to 6.0 for Release, and to 5.1 for Debug, not sure why). I had to recompile the project, and for some reason, it did compile the library, but failed to package the things correctly. I just copied the missing stuff from 1.2.3 version. In any case, now it doesnt crash and works both on emulator 6.0 and device 5.1.1 (the test on device 6.0 is not done yet)

**Comment by schmoove** [comment]
App still crashing on iOS 5.1 device with original error message I'm afraid

**Comment by annakozy2011** [comment]
Well, I am not sure about iOS 5.1, but on 5.1.1 it´s not crashing.... You can check this app, if you want:

itms://itunes.apple.com/us/app/comfia.cat/id580824835?mt=8.

**Comment by annakozy2011** [comment]
But I compiled my own version of the library, like I said...

**Comment by annakozy2011** [comment]
Well, I am not 100% sure now, but I think I also ensured the correct (4.3) target version for my PROJECT (not for the library). I think I modified 2.1.4.GA Titanium SDK somehow to make sure it always creates the project with 4.0 or 4.3 target version. It´s not complicated, I just cant find the "pure" 2.1.4.GA now, so that I could compare my files...

**Comment by ChrisRM** [comment]
New version coming up.

**Comment by annakozy2011** [comment]
It actually only crashed on 5.x, if at all... it never crashed on 6.x

**Comment by ChrisRM** [comment]
Are you able to test it on 5.x ?

**Comment by annakozy2011** [comment]
No, sorry, I already finished and submitted to appstore the app, and also I used a modified version in it...

**Comment by ChrisRM** [comment]
Ok, waiting for @syngency

**Comment by schmoove** [comment]
Still same result on 5.1:

```
[INFO] [object AgCalendarModule] loaded
[DEBUG] Loading: /var/mobile/Applications/19EADF0C-A5A5-48AB-9026-EBC06EA40666/Syngency.app/ag.calendar.js, Resource: ag_calendar_js
dyld: lazy symbol binding failed: Symbol not found: _objc_setProperty_nonatomic
Referenced from: /var/mobile/Applications/19EADF0C-A5A5-48AB-9026-EBC06EA40666/Syngency.app/Syngency
Expected in: /usr/lib/libobjc.A.dylib

dyld: Symbol not found: _objc_setProperty_nonatomic
Referenced from: /var/mobile/Applications/19EADF0C-A5A5-48AB-9026-EBC06EA40666/Syngency.app/Syngency
Expected in: /usr/lib/libobjc.A.dylib
```

Not crashing the app anymore but halting execution

**Comment by ChrisRM** [comment]
Please try one more time @syngency :-) Use ag.calendar-iphone-1.2.5.zip

**Comment by schmoove** [comment]
Yep, 1.2.5 works a charm- thanks so much for sorting that Chris!
