### ISSUE TITLE
Issue with Displaying multiple events from datasource

### ISSUE THREAD

**Issue by Corliosity** [Appgutta/AGCalendar#20]
Hello,

I am trying to use the calendar and display multiple events from a JSON file but these become duplicated in coredata and do not show in eventkit.  I have tried using the temp fix to no avail.  is there a solution on the way?  I am willing to pay if that will help.

Thank you,

**Comment by Corliosity** [comment]
I think I may have found the problem.  This error seems to exists because of the identifier duplication.  If while using coredata you have the identifier set to offer an info statement will print "An event with the same identifier already exists."  Could it be possible to use this method to keep multiple events from showing?

![Screen Shot 2012-12-11 at 9 52 04 AM](https://f.cloud.github.com/assets/1386170/6233/68f38242-43b2-11e2-9c78-f8125a76a9ed.png)

**Comment by ChrisRM** [comment]
Please gist or send me the file that uses the calendar, and I'll see what I can do.

**Comment by Corliosity** [comment]
OK, I am attaching the code with the events call and the calendar display.

Thank you for your help,

-Andrew

**Comment by ChrisRM** [comment]
Waiting for the code...

**Comment by Corliosity** [comment]
Sorry for the delay and forgetting to include code.

The gist file is located here:

https://gist.github.com/db4dbb8c79536da5500f

**Comment by ChrisRM** [comment]
https://gist.github.com/db4dbb8c79536da5500f#comment-632123

**Comment by Corliosity** [comment]
Hey Chris,

Thanks for the fix.

However I have noticed that since 1.2.5 and 1.2.6 came out I can no longer display my data from an external source.  I have my code on a gist account here: https://gist.github.com/cf429a90f3622e327c59

Do you know the reason?

**Comment by clseva** [comment]
It's a bug. Chris is working on it. 
See: https://github.com/Appgutta/AGCalendar/issues/23

**Comment by Corliosity** [comment]
Thanks

**Comment by Corliosity** [comment]
Hey Chris when using Coredata as the data source we still get event duplication even when passing a timeout function.  Can you take a quick look for me please? Thanks!

https://gist.github.com/8deee7d1a7e6af371676

Or could it be a problem with how I am calling and adding data?

Sorry for taking up time but thank you for all of your help.

**Comment by Corliosity** [comment]
This is what i got from one of our other developers working on the issue:

The only problem I see in here is that events are being added every time the app runs.
The identifier we get from Ti.Calendar.identifier generates a new hash at each request, that makes me think this could be the source of the problem.

**Comment by Corliosity** [comment]
Sorry for opening and re-opening my group has figured out a way to solve this problem through the API:

What do you guys think if we create our on fix?
Is it easy to send another parameter with the JSON?
Let's say we send a udid along each event. When we events: If they have a different UDID, we add it, otherwise the module verifies on its own that the event already exists and don't add it :)

The unique identifier keeps it so that the events will not appear more than once.
