### ISSUE TITLE
All-day event

### ISSUE THREAD

**Issue by joakimkanon** [Appgutta/AGCalendar#21]
Is it possible to create an all-day event, with just date and no time?

![all-day](https://f.cloud.github.com/assets/3052031/15125/6330460e-46fc-11e2-8741-f207d2813a3f.png)

**Comment by ChrisRM** [comment]
Hmm, not in the current build. I'll add it asap

**Comment by joakimkanon** [comment]
Awesome! Thanks a bunch.

Very nice module, btw. :)

**Comment by ChrisRM** [comment]
Thanks :-) It'll be available tomorrow morning, Norwegian time (CET+1). Any other request while we're at it ?

**Comment by joakimkanon** [comment]
Kjempeflott! ;D
No, no more requests at the moment.

**Comment by ChrisRM** [comment]
Fixed in version 2.0, will be merged in version 1.3
