### ISSUE TITLE
Longclick event

### ISSUE THREAD

**Issue by clseva** [Appgutta/AGCalendar#22]
Hi Chris, great module.

Is it possible to detect "longclick" event when you select some date? For example, it would be great to have "date:longclick" or "date:longclicked" to add a new event. Also, it could return the selected date like "date:clicked". Would this be very tricky to do?

Thanks and great work!!

**Comment by ChrisRM** [comment]
Fixed! See https://github.com/Appgutta/AGCalendar#datelongpress

**Comment by clseva** [comment]
Great! It works correctly! Thank you so much!!
