### ISSUE TITLE
Find and return a stored Event. 

### ISSUE THREAD

**Issue by aaronce** [Appgutta/AGCalendar#24]
Hi Chris,
I was wondering if there is anyway to find and return an event in this module, I've had a quick look and couldn't see anything that stood out to me, is the only way to access the event through an 'event:clicked'..? 

I was thinking it might be useful to have a function that could accept an event's identifier and return the details as an array.

Aaron.

**Comment by ChrisRM** [comment]
This feature is on the roadmap for version 1.3, but I might just include it in 1.2.8 if all goes well. I'll see what I can do.

**Comment by aaronce** [comment]
nice. thanks for the info.
