### ISSUE TITLE
ipad view changed?

### ISSUE THREAD

**Issue by soyoh** [Appgutta/AGCalendar#31]
Hello,
i was using your module, that works great, but today i've update to las version you pushed, and now iPad view is different??
i mean, before ipad show opened big on window (like native), but now i just opened like on iphone: small at tope left.

this is a normal behavior??
thanks

**Comment by ChrisRM** [comment]
I had to change it to support UIPopoverView on iPad instead, as Apple was rejecting the fullscreen version. See Issue #25

**Comment by soyoh** [comment]
ah ok i see.
so on iPad is not possible to use a calendar in full view?? this will just make change all desing on my app..

thanks!!

**Comment by ChrisRM** [comment]
Im working on an update that scales the calendar according to the parent view. I'll let you know when its ready.

**Comment by soyoh** [comment]
ok, awesome. thank you !
