### ISSUE TITLE
no identifier supplied in answer from fetchEvents

### ISSUE THREAD

**Issue by jonasthoor** [Appgutta/AGCalendar#34]
When fetching events from the EventKit your documentation says "When using Core Data your custom identifier is returned, else the auto generated eventIdentifier in EventKit is returned.".

Still the object received contains no identifier...
{"title":"AAA - BBB","startDate":"2013-03-31T15:30:00.000Z","location":"CCC","endDate":"2013-03-31T17:30:00.000Z","alarmOffset":"-86400.000000"}

is the only data i receive when i just JSON.stringify() the returned object.

**Comment by sschua74** [comment]
Hi chris,

Still the same for ver 1.2.8. It does not contain the identifier.
I am using iphone 4s ios 6.1.2, titanium SDK 3.0.2
