### ISSUE TITLE
no identifier supplied in answer from fetchEvents

### ISSUE THREAD

**Issue by sschua74** [Appgutta/AGCalendar#37]
Hi chris,

Still having the same issue, event identifier never return in fetchEvents
I am using ag.calendar 1.2.8, iphone4s ios 6.1.2. Titanium SDK 3.02.
Thanks

**Comment by ChrisRM** [comment]
1.2.9 with this and a couple other fixes will be released later today or tomorrow.

**Comment by ChrisRM** [comment]
Fixed in version 2.0, will be merged in version 1.3
