### ISSUE TITLE
Ti.Calendar.getEvents() returns null

### ISSUE THREAD

**Issue by joseandro** [Appgutta/AGCalendar#38]
Hi Chris,

When using version 1.2.8, the API call Ti.Calendar.getEvents() always returns null (even when there are more than 100 events previously subscribed for the current year).

Is this a bug?
When do you plan to release the version 2.0 ?
Can't wait ;)

Thanks

**Comment by ChrisRM** [comment]
The plan was to release it on friday the 15th, but I've had to much to do at work. I'll release it by the end of the week.

In the meantime, I'll upload 1.2.9 which will fix this issue and a couple others later today or tomorrow night.

**Comment by ashishraghavan** [comment]
Great. I have also been having the same issue and trying to figure out why is it so. By the way, thanks for this awesome module.

**Comment by joseandro** [comment]
I'd really appreciate it, Chris!
I look forward to see it working :)

Thanks

**Comment by ChrisRM** [comment]
Fixed in version 2.0, will be merged in version 1.3
