### ISSUE TITLE
Alert (Reminder) option for Events

### ISSUE THREAD

**Issue by mattberg** [Appgutta/AGCalendar#8]
Great module. I was wondering if it would be possible to add Alerts (reminders) to an event that is added? Similar to how you can add one when adding an event in iCal on the phone. Thanks.

**Comment by ChrisRM** [comment]
Sure, I'll add it later this week. In iOS 6 we will have access to the reminders sdk aswell, so I might be adding some new cool features in the coming days.

**Comment by vanbungkring** [comment]
hello, can i customize this calendar like http://i.stack.imgur.com/VqfEM.png??? need it urgently

**Comment by mattberg** [comment]
Thanks Chris, I appreciate it.

**Comment by ChrisRM** [comment]
@vanbungkring You are free to customize the calendar as you like. The only requirement is that you keep it open source.
